### ISSUE TITLE
Clicking Arrange by shows a floating menu quite out of place

### ISSUE THREAD

**Issue by garuma** [xamarin/Xamarin.PropertyEditing#365] opened 2018-08-16 18:26 UTC
Originally reported by @kzu on VSTS.

![image](https://user-images.githubusercontent.com/104105/44227332-53395a00-a160-11e8-886e-bd5b38305398.png)

**Comment by ermau** [comment] 2018-08-16 18:27
Dupe of #331

**Closed by ermau** 2018-08-16 18:27 UTC
